### PR TITLE
Fixed recursive clustering log in Line 1516 & Subset lib.size in  Line 2551

### PR DESCRIPTION
**Pull request by JasonLiZhou**

### CODE REVIEW

**Review by iaconogi — COMMENTED** [review]
No, lib.size is subsetted later as an input to DE_Rcpp().
Thanks for the observation anyway.
Giovanni

**Comment by JasonLiZhou** [comment]
However it seems that group1 & group2 has been changed on line 2562, so I wonder whether the later subset was correcct

> bigscale_group

> bigscale_group-2

**Comment by iaconogi** [comment]
You are right. Incredible that this nasty bug has survived so long.

**Comment by JasonLiZhou** [comment]
One more thing, I wonder whether the 'mean(lib.size)'  in Line 2718 referring to the average lib.size of only group1 & group2, or the average of all groups.

> mean(lib size)

**Pull request closed without merging**
